### PR TITLE
Updated color functionality

### PR DESCRIPTION
**Pull request by siddarth-patil**
Now random colors will be allocated to the categories for which the color is not specified explicitly. Updated the GIF, Readme, Test_module, and example code as well.

### CODE REVIEW

**Comment by lucharo** [comment]
Hi @siddarth-patil thanks for refactoring, there's still a few old commits. I'll take the last commit (the only one containing a change from master) and merge to master over the weekend.

**Comment by siddarth-patil** [comment]
> Hi @siddarth-patil thanks for refactoring, there's still a few old commits. I'll take the last commit (the only one containing a change from master) and merge to master over the weekend.

Thanks a lot @lc5415 Is it common to get conflicts? Please let me know what can I do to make sure that there are no conflicts next time. 

Also, I read somewhere that it is better to link pull requests to issues. So, should we also follow the same from next time?

**Comment by lucharo** [comment]
Hi @siddarth-patil, I've finally made some time to take care of this, sorry for the delay. 

Looking back, I suspect the problem was I merged your initial PR from the `update_01-color-functionality`  branch and then made some more changes (documentation or whatnot). Then you kept on adding the random-color-if-not-specified feature in your original branch but you didn't take into account the further changes I made in the middle (in that case you should have pulled the changes from my main branch if you wanted to continue from the first branch or simply create another branch/fork from my updated main branch). In general I prefer the latter method where every new feature stems from the latest version of the branching you are submitting a PR into. Though this is very context dependent. 

Thanks for your contribution

**Comment by siddarth-patil** [comment]
Hi @lucharo, thanks a lot. I will take care of these conflicts the next time. Lemme know if there is some other functionality in your mind that could be added to this package, I would like to work on it.

**Comment by lucharo** [comment]
Ok, great @siddarth-patil, I would recommend closing/deleting your `update-colour-functionality` branch in your raceplotly fork now and if at some point in the future you think of a new feature you wanna add then you should a create a branch for that specific feature and then later a PR!

**Pull request merged**
